worker-threads: 4
worker-fs-threads: 2
logger-level: info

is-testing: false

server-port: 8080

auth-service-grpc-endpoint: localhost:8094
target-service-grpc-endpoint: localhost:8090
monitor-service-grpc-endpoint: localhost:8091
alert-service-grpc-endpoint: localhost:8092
notification-service-grpc-endpoint: localhost:8093
