worker-threads: 4
worker-fs-threads: 2
logger-level: info

is-testing: false

server-port: 8080

auth-service-grpc-endpoint: auth-service:8094
target-service-grpc-endpoint: target-service:8090
monitor-service-grpc-endpoint: monitor-service:8091
alert-service-grpc-endpoint: alert-service:8092
notification-service-grpc-endpoint: notification-service:8093
