worker-threads: 4
worker-fs-threads: 2
logger-level: info

is-testing: false

server-port: 8080
grpc-server-port: 8091

scheduler-enabled: true
scheduler-scan-period-ms: 1000
scheduler-lease-duration-ms: 30000

target-service-grpc-endpoint: localhost:8090
alert-service-grpc-endpoint: localhost:8092
# change to URI of your postgres database
pg-connection: postgresql://testsuite@localhost:15433/monitor_service_netwatch_db
