worker-threads: 4
worker-fs-threads: 2
logger-level: info

is-testing: false

server-port: 8080
grpc-server-port: 8091

scheduler-enabled: true
scheduler-scan-period-ms: 1000
scheduler-lease-duration-ms: 30000

target-service-grpc-endpoint: target-service:8090
alert-service-grpc-endpoint: alert-service:8092
pg-connection: postgresql://monitor_service:monitor_service@monitor-postgres:5432/monitor_service_db
