worker-threads: 4
worker-fs-threads: 2
logger-level: info

is-testing: false

server-port: 8080
grpc-server-port: 8091

scheduler-enabled: true
scheduler-scan-period-ms: 1000

target-service-grpc-endpoint: target-service:8090
pg-connection: postgresql://netwatch:netwatch@postgres:5432/netwatch_db
