worker-threads: 4
worker-fs-threads: 2
logger-level: info

is-testing: false

server-port: 8080
grpc-server-port: 8092

pg-connection: postgresql://testsuite@localhost:15433/alert_service_netwatch_db
