worker-threads: 4
worker-fs-threads: 2
consumer-worker-threads: 1
consumer-blocking-worker-threads: 1
logger-level: info

is-testing: false

server-port: 8080
grpc-server-port: 8093

pg-connection: postgresql://notification_service:notification_service@notification-postgres:5432/notification_service_db
secdist-path: configs/secdist.compose.json

notification-consumer-enabled: true
alert-events-topic: netwatch.alert.events.v1
notification-consumer-group: netwatch.notification-service.v1
notification-consumer-max-batch-size: 50
notification-consumer-poll-timeout: 1s
notification-consumer-restart-after-failure-delay: 5s
notification-consumer-auto-offset-reset: largest

notification-email-sender-enabled: true
notification-email-provider: mailpit
notification-email-provider-url: http://mailpit:8025
notification-email-from-email: netwatch@example.test
notification-email-from-name: NetWatch
notification-email-seed-recipient-email: alerts@example.test
notification-email-sender-batch-size: 20
notification-email-sender-period-ms: 1000
notification-email-request-timeout-ms: 3000
notification-email-max-attempts: 3
notification-email-retry-delay-ms: 30000
notification-yandex-postbox-iam-token: ''
notification-yandex-postbox-metadata-token-url: http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token
notification-yandex-postbox-token-refresh-skew-sec: 300
